2022-08-01 08:01:08,678 INFO     ---------------------------------------------------------------------------------------------
2022-08-01 08:01:08,678 INFO     Geo: cqd
2022-08-01 08:01:08,678 INFO     Data Path: data/FB15k-237-betae
2022-08-01 08:01:08,678 INFO     #entity: 14505
2022-08-01 08:01:08,678 INFO     #relation: 474
2022-08-01 08:01:08,679 INFO     #max steps: 150000
2022-08-01 08:01:08,679 INFO     Evaluate unoins using: DNF
2022-08-01 08:01:08,679 INFO     loading data
2022-08-01 08:01:48,890 INFO     Training info:
2022-08-01 08:01:48,894 INFO     2p: 149689
2022-08-01 08:01:50,962 INFO     Validation info:
2022-08-01 08:01:50,962 INFO     2p: 5000
2022-08-01 08:01:50,964 INFO     Test info:
2022-08-01 08:01:50,964 INFO     2p: 5000
2022-08-01 08:01:53,477 INFO     Model Parameter Configuration:
2022-08-01 08:01:53,477 INFO     Parameter embeddings.0.weight: torch.Size([14505, 2000]), require_grad = True
2022-08-01 08:01:53,477 INFO     Parameter embeddings.1.weight: torch.Size([474, 2000]), require_grad = True
2022-08-01 08:01:53,477 INFO     Parameter Number: 29958000
2022-08-01 08:01:53,553 INFO     Loading checkpoint models/fb15k-237-betae...
2022-08-01 08:01:54,065 INFO     tasks = 2p
2022-08-01 08:01:54,065 INFO     init_step = 99999
2022-08-01 08:01:54,065 INFO     Start Training...
2022-08-01 08:01:54,065 INFO     learning_rate = 0
2022-08-01 08:01:54,065 INFO     batch_size = 1024
2022-08-01 08:01:54,065 INFO     hidden_dim = 1000
2022-08-01 08:01:54,065 INFO     gamma = 12.000000
posix.uname_result(sysname='Linux', nodename='gonzo-605-6.local', release='3.10.0-1160.49.1.el7.x86_64', version='#1 SMP Tue Nov 30 15:51:32 UTC 2021', machine='x86_64')
Traceback (most recent call last):
  File "main.py", line 632, in <module>
    main(parse_args())
  File "main.py", line 537, in main
    log = KGReasoning.train_step(model, optimizer, train_path_iterator, args, step)
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/models.py", line 674, in train_step
    model.forward(positive_sample=positive_sample,
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/base.py", line 439, in forward
    scores = d2.query_2p(entity_embeddings=self.embeddings[0],
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/discrete.py", line 93, in query_2p
    atom2_scores_2d, _ = score_candidates(s_emb=x1_k_emb_2d, p_emb=p2_emb,
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/discrete.py", line 33, in score_candidates
    atom_scores_2d = scoring_function(s_emb, p_emb, candidates_emb)
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/base.py", line 586, in scoring_function
    res, _ = self.score_o(lhs_, rel_, rhs_)
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/base.py", line 252, in score_o
    return score_1 + score_2, factors
RuntimeError: CUDA out of memory. Tried to allocate 3.54 GiB (GPU 0; 10.92 GiB total capacity; 9.06 GiB already allocated; 1.16 GiB free; 9.08 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
