2022-07-30 06:58:11,675 INFO     ---------------------------------------------------------------------------------------------
2022-07-30 06:58:11,675 INFO     Geo: cqd
2022-07-30 06:58:11,675 INFO     Data Path: data/FB15k-237-betae
2022-07-30 06:58:11,675 INFO     #entity: 14505
2022-07-30 06:58:11,675 INFO     #relation: 474
2022-07-30 06:58:11,675 INFO     #max steps: 150000
2022-07-30 06:58:11,675 INFO     Evaluate unoins using: DNF
2022-07-30 06:58:11,675 INFO     loading data
2022-07-30 06:58:48,084 INFO     Training info:
2022-07-30 06:58:48,090 INFO     2p: 149689
2022-07-30 06:58:50,079 INFO     Validation info:
2022-07-30 06:58:50,079 INFO     2p: 5000
2022-07-30 06:58:50,081 INFO     Test info:
2022-07-30 06:58:50,081 INFO     2p: 5000
2022-07-30 06:58:52,562 INFO     Model Parameter Configuration:
2022-07-30 06:58:52,562 INFO     Parameter embeddings.0.weight: torch.Size([14505, 2000]), require_grad = True
2022-07-30 06:58:52,562 INFO     Parameter embeddings.1.weight: torch.Size([474, 2000]), require_grad = True
2022-07-30 06:58:52,562 INFO     Parameter Number: 29958000
2022-07-30 06:58:52,590 INFO     Loading checkpoint models/fb15k-237-betae...
2022-07-30 06:58:52,728 INFO     tasks = 2p
2022-07-30 06:58:52,728 INFO     init_step = 99999
2022-07-30 06:58:52,728 INFO     Start Training...
2022-07-30 06:58:52,728 INFO     learning_rate = 0
2022-07-30 06:58:52,729 INFO     batch_size = 4096
2022-07-30 06:58:52,729 INFO     hidden_dim = 1000
2022-07-30 06:58:52,729 INFO     gamma = 12.000000
posix.uname_result(sysname='Linux', nodename='rowlf.local', release='3.10.0-1160.49.1.el7.x86_64', version='#1 SMP Tue Nov 30 15:51:32 UTC 2021', machine='x86_64')
Traceback (most recent call last):
  File "main.py", line 632, in <module>
    main(parse_args())
  File "main.py", line 537, in main
    log = KGReasoning.train_step(model, optimizer, train_path_iterator, args, step)
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/models.py", line 674, in train_step
    model.forward(positive_sample=positive_sample,
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/base.py", line 439, in forward
    scores = d2.query_2p(entity_embeddings=self.embeddings[0],
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/discrete.py", line 93, in query_2p
    atom2_scores_2d, _ = score_candidates(s_emb=x1_k_emb_2d, p_emb=p2_emb,
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/discrete.py", line 33, in score_candidates
    atom_scores_2d = scoring_function(s_emb, p_emb, candidates_emb)
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/base.py", line 586, in scoring_function
    res, _ = self.score_o(lhs_, rel_, rhs_)
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/base.py", line 250, in score_o
    score_2 = (lhs[1] * rel[0] + lhs[0] * rel[1]) @ rhs[1].transpose(-1, -2)
RuntimeError: CUDA out of memory. Tried to allocate 7.08 GiB (GPU 0; 15.90 GiB total capacity; 10.71 GiB already allocated; 4.38 GiB free; 10.72 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
