2022-07-28 11:07:55,545 INFO     ---------------------------------------------------------------------------------------------
2022-07-28 11:07:55,545 INFO     Geo: cqd
2022-07-28 11:07:55,545 INFO     Data Path: data/FB15k-237-betae
2022-07-28 11:07:55,545 INFO     #entity: 14505
2022-07-28 11:07:55,545 INFO     #relation: 474
2022-07-28 11:07:55,545 INFO     #max steps: 150000
2022-07-28 11:07:55,545 INFO     Evaluate unoins using: DNF
2022-07-28 11:07:55,545 INFO     loading data
2022-07-28 11:08:47,428 INFO     Training info:
2022-07-28 11:08:47,438 INFO     2p: 149689
2022-07-28 11:08:50,232 INFO     Validation info:
2022-07-28 11:08:50,233 INFO     2p: 5000
2022-07-28 11:08:50,236 INFO     Test info:
2022-07-28 11:08:50,236 INFO     2p: 5000
posix.uname_result(sysname='Linux', nodename='gonzo-605-20.local', release='3.10.0-1160.49.1.el7.x86_64', version='#1 SMP Tue Nov 30 15:51:32 UTC 2021', machine='x86_64')
Traceback (most recent call last):
  File "main.py", line 632, in <module>
    main(parse_args())
  File "main.py", line 425, in main
    model = CQD(nentity,
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/base.py", line 191, in __init__
    self.batch_entity_range = self.batch_entity_range.cuda()
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
