2022-08-08 17:26:50,358 INFO     ---------------------------------------------------------------------------------------------
2022-08-08 17:26:50,359 INFO     Geo: cqd
2022-08-08 17:26:50,359 INFO     Data Path: data/FB15k-237-betae
2022-08-08 17:26:50,359 INFO     #entity: 14505
2022-08-08 17:26:50,359 INFO     #relation: 474
2022-08-08 17:26:50,359 INFO     #max steps: 150000
2022-08-08 17:26:50,359 INFO     Evaluate unoins using: DNF
2022-08-08 17:26:50,359 INFO     loading data
2022-08-08 17:27:22,141 INFO     Training info:
2022-08-08 17:27:22,144 INFO     Validation info:
2022-08-08 17:27:22,146 INFO     up-DNF: 5000
2022-08-08 17:27:22,149 INFO     Test info:
2022-08-08 17:27:22,149 INFO     up-DNF: 5000
/home/shinaliu/miniconda3/envs/kg/lib/python3.8/site-packages/torch/cuda/__init__.py:145: UserWarning: 
NVIDIA A100-PCIE-40GB with CUDA capability sm_80 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
If you want to use the NVIDIA A100-PCIE-40GB GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
2022-08-08 17:27:22,508 INFO     Model Parameter Configuration:
2022-08-08 17:27:22,508 INFO     Parameter embeddings.0.weight: torch.Size([14505, 2000]), require_grad = False
2022-08-08 17:27:22,509 INFO     Parameter embeddings.1.weight: torch.Size([474, 2000]), require_grad = False
2022-08-08 17:27:22,509 INFO     Parameter Number: 0
2022-08-08 17:27:22,522 INFO     Loading checkpoint models/fb15k-237-betae...
2022-08-08 17:27:22,634 INFO     tasks = up
2022-08-08 17:27:22,634 INFO     init_step = 99999
2022-08-08 17:27:22,635 INFO     batch_size = 1024
2022-08-08 17:27:22,635 INFO     hidden_dim = 1000
2022-08-08 17:27:22,635 INFO     gamma = 12.000000
2022-08-08 17:27:22,635 INFO     Evaluating on Valid Dataset...
posix.uname_result(sysname='Linux', nodename='bert.local', release='3.10.0-1160.49.1.el7.x86_64', version='#1 SMP Tue Nov 30 15:51:32 UTC 2021', machine='x86_64')
99999
  0%|          | 0/5000 [00:00<?, ?it/s]  0%|          | 0/5000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "main.py", line 632, in <module>
    main(parse_args())
  File "main.py", line 620, in main
    valid_all_metrics = evaluate(model, valid_easy_answers, valid_hard_answers, args, valid_dataloader, query_name_dict, 'Valid', step, writer)
  File "main.py", line 203, in evaluate
    metrics = KGReasoning.test_step(model, tp_answers, fn_answers, args, dataloader, query_name_dict)
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/models.py", line 974, in test_step
    _, negative_logit, _, idxs = model(None, negative_sample, None, batch_queries_dict, batch_idxs_dict)
  File "/home/shinaliu/miniconda3/envs/kg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/base.py", line 337, in forward
    atoms, num_variables, conjunction_mask, negation_mask = query_to_atoms(query_structure, queries)
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/util.py", line 41, in query_to_atoms
    triples[:, 2] = variable
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
