2022-08-08 17:47:39,782 INFO     ---------------------------------------------------------------------------------------------
2022-08-08 17:47:39,782 INFO     Geo: cqd
2022-08-08 17:47:39,782 INFO     Data Path: data/FB15k-237-betae
2022-08-08 17:47:39,782 INFO     #entity: 14505
2022-08-08 17:47:39,782 INFO     #relation: 474
2022-08-08 17:47:39,782 INFO     #max steps: 150000
2022-08-08 17:47:39,782 INFO     Evaluate unoins using: DNF
2022-08-08 17:47:39,782 INFO     loading data
2022-08-08 17:48:13,247 INFO     Training info:
2022-08-08 17:48:13,250 INFO     3p: 149689
2022-08-08 17:48:16,608 INFO     Validation info:
2022-08-08 17:48:16,608 INFO     3p: 5000
2022-08-08 17:48:16,610 INFO     Test info:
2022-08-08 17:48:16,610 INFO     3p: 5000
2022-08-08 17:48:18,882 INFO     Model Parameter Configuration:
2022-08-08 17:48:18,883 INFO     Parameter embeddings.0.weight: torch.Size([14505, 2000]), require_grad = True
2022-08-08 17:48:18,883 INFO     Parameter embeddings.1.weight: torch.Size([474, 2000]), require_grad = True
2022-08-08 17:48:18,883 INFO     Parameter Number: 29958000
2022-08-08 17:48:18,910 INFO     Loading checkpoint models/fb15k-237-betae...
2022-08-08 17:48:19,059 INFO     tasks = 3p
2022-08-08 17:48:19,059 INFO     init_step = 99999
2022-08-08 17:48:19,059 INFO     Start Training...
2022-08-08 17:48:19,059 INFO     learning_rate = 0
2022-08-08 17:48:19,059 INFO     batch_size = 1024
2022-08-08 17:48:19,059 INFO     hidden_dim = 1000
2022-08-08 17:48:19,059 INFO     gamma = 12.000000
posix.uname_result(sysname='Linux', nodename='bobo.local', release='3.10.0-1160.49.1.el7.x86_64', version='#1 SMP Tue Nov 30 15:51:32 UTC 2021', machine='x86_64')
Traceback (most recent call last):
  File "main.py", line 632, in <module>
    main(parse_args())
  File "main.py", line 537, in main
    log = KGReasoning.train_step(model, optimizer, train_path_iterator, args, step)
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/models.py", line 674, in train_step
    model.forward(positive_sample=positive_sample,
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/base.py", line 445, in forward
    scores = d2.query_3p(entity_embeddings=self.embeddings[0],
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/discrete.py", line 163, in query_3p
    res = t_norm(atom1_scores_3d, atom2_scores_3d)
  File "/home/shinaliu/miniconda3/envs/kg/lib/python3.8/site-packages/torchnorms/tnorms/classic.py", line 28, in __call__
    return a * b
RuntimeError: CUDA out of memory. Tried to allocate 3.54 GiB (GPU 0; 15.90 GiB total capacity; 12.80 GiB already allocated; 2.03 GiB free; 13.07 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
