2022-07-28 10:49:02,845 INFO     ---------------------------------------------------------------------------------------------
2022-07-28 10:49:02,845 INFO     Geo: cqd
2022-07-28 10:49:02,845 INFO     Data Path: data/FB15k-237-betae
2022-07-28 10:49:02,845 INFO     #entity: 14505
2022-07-28 10:49:02,845 INFO     #relation: 474
2022-07-28 10:49:02,845 INFO     #max steps: 150000
2022-07-28 10:49:02,846 INFO     Evaluate unoins using: DNF
2022-07-28 10:49:02,846 INFO     loading data
2022-07-28 10:49:48,545 INFO     Training info:
2022-07-28 10:49:48,549 INFO     2p: 149689
2022-07-28 10:49:50,770 INFO     Validation info:
2022-07-28 10:49:50,771 INFO     2p: 5000
2022-07-28 10:49:50,773 INFO     Test info:
2022-07-28 10:49:50,773 INFO     2p: 5000
posix.uname_result(sysname='Linux', nodename='sweetums-609-7.local', release='3.10.0-1160.66.1.el7.x86_64', version='#1 SMP Wed May 18 16:02:34 UTC 2022', machine='x86_64')
Traceback (most recent call last):
  File "main.py", line 632, in <module>
    main(parse_args())
  File "main.py", line 425, in main
    model = CQD(nentity,
  File "/home/shinaliu/KG/models/kg-reasoning-alpha/cqd/base.py", line 191, in __init__
    self.batch_entity_range = self.batch_entity_range.cuda()
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
