2022-07-28 10:57:57,117 INFO     ---------------------------------------------------------------------------------------------
2022-07-28 10:57:57,117 INFO     Geo: cqd
2022-07-28 10:57:57,117 INFO     Data Path: data/FB15k-237-betae
2022-07-28 10:57:57,118 INFO     #entity: 14505
2022-07-28 10:57:57,118 INFO     #relation: 474
2022-07-28 10:57:57,118 INFO     #max steps: 150000
2022-07-28 10:57:57,118 INFO     Evaluate unoins using: DNF
2022-07-28 10:57:57,118 INFO     loading data
2022-07-28 10:58:34,610 INFO     Training info:
2022-07-28 10:58:34,614 INFO     Validation info:
2022-07-28 10:58:34,616 INFO     pi: 5000
2022-07-28 10:58:34,619 INFO     Test info:
2022-07-28 10:58:34,619 INFO     pi: 5000
2022-07-28 10:58:37,521 INFO     Model Parameter Configuration:
2022-07-28 10:58:37,521 INFO     Parameter embeddings.0.weight: torch.Size([14505, 2000]), require_grad = True
2022-07-28 10:58:37,521 INFO     Parameter embeddings.1.weight: torch.Size([474, 2000]), require_grad = True
2022-07-28 10:58:37,521 INFO     Parameter Number: 29958000
posix.uname_result(sysname='Linux', nodename='gonzo-605-9.local', release='3.10.0-1160.49.1.el7.x86_64', version='#1 SMP Tue Nov 30 15:51:32 UTC 2021', machine='x86_64')
Traceback (most recent call last):
  File "main.py", line 632, in <module>
    main(parse_args())
  File "main.py", line 486, in main
    model = model.cuda()
  File "/home/shinaliu/miniconda3/envs/kg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 688, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/shinaliu/miniconda3/envs/kg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/shinaliu/miniconda3/envs/kg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/shinaliu/miniconda3/envs/kg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/home/shinaliu/miniconda3/envs/kg/lib/python3.8/site-packages/torch/nn/modules/module.py", line 688, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
